# See: https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
name: Release Assets


on:
  workflow_dispatch:
jobs:
  release_assets_mac_linux:
    name: Release Assets Mac and Linux
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
#          - os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sbt "resplitEpollApp/nativeLink"
      - name: Move
        run: cp resplitEpollApp/target/scala-3.2.2/resplitepollapp-out resplit_${{ matrix.config.os }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: resplit_${{ matrix.config.os }}
      - name: Check if works
        run: cat testfile | resplit_${{ matrix.config.os }} '(dog)\d' '$1' -d tmp
      #  release_assets_windows:
#    name: Release Assets Windows
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Release
#        run: sbt "resplitIOApp/nativeLink"
#      - name: Move
#        run: cp resplitIOApp/target/scala-3.2.2/resplitioapp-out resplit-windows