# See: https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
name: Release Assets

env:
  SCALA_VERSION: '3.2.2'

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  release_assets:
    name: Release Assets
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build executable
        if: ${{ matrix.config.os != 'windows-latest' }}
        run: |
          sbt ";set nativeMode := scala.scalanative.build.Mode.releaseSize.name; nativeLink" &&
          cp target/scala-3.2.2/resplit-out resplit-${{ matrix.config.os }}
      - name: Build executable
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: |
          sbt ";set nativeMode := scala.scalanative.build.Mode.releaseSize.name; nativeLink" && 
          cp target/scala-3.2.2/resplit-out.exe resplit-${{ matrix.config.os }}.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resplit-${{ matrix.config.os }}
            resplit-${{ matrix.config.os }}.exe