# See: https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/
name: Release Assets


on:
  workflow_dispatch:
jobs:
  release_assets_mac_linux:
    name: Release Assets Mac and Linux
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: sbt nativeLink
  release_assets_windows:
    name: Release Assets
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: sbt "resplitEpollApp/nativeLink"